const app = document.querySelector('#app');
const videoInput = document.querySelector('#videoInput');
let activeView = 'overview';
let gps = { lat: 28.6139, lng: 77.2090, source: 'MISSION HOME' };
let counts = { people: 12, animals: 3, vehicles: 8, objects: 4 };
let threat = 68;

const alerts = [
  ['HIGH', 'Elephant herd detected', '1.8 km NE / wildlife corridor', '02:14'],
  ['MED', 'Unattended object flagged', 'Bag-04 / dwell 08:42', '01:48'],
  ['LOW', 'Vehicle track changed course', 'V-12 / north perimeter', '00:57'],
];

function panel(title, note, body, live = false) {
  return `<section class="panel"><div class="panel-head"><h2>${title}</h2><span class="${live ? 'live' : ''}">${note}</span></div>${body}</section>`;
}
function metric(value, name, color = '') { return `<div class="metric"><div class="metric-value ${color}">${value}</div><div class="metric-name">${name}</div></div>`; }
function alertList() { return `<div class="alert-list">${alerts.map(([level, copy, detail, time]) => `<div class="alert"><span class="alert-mark ${level === 'LOW' ? 'cyan' : ''}"></span><div class="alert-copy"><strong>${copy}</strong><small>${detail}</small></div><span class="alert-time">${time}</span></div>`).join('')}</div>`; }
function map() { return `<div class="map"><div class="map-grid"></div><span class="map-tag tag-n">N ↑ / 360°</span><span class="map-tag tag-live">● GPS LOCKED</span><div class="map-ring"></div><div class="map-center"></div><span class="contact a" data-name="WILDLIFE"></span><span class="contact b" data-name="V-12"></span><span class="contact c" data-name="P-08"></span><span class="contact d" data-name="OBJ-04"></span><span class="map-tag tag-scale">RANGE 2.4 KM</span></div><div class="legend"><span><i style="background:var(--lime)"></i>UNIT 01</span><span><i style="background:var(--red)"></i>THREAT / WILDLIFE</span><span><i style="background:var(--amber)"></i>VEHICLE</span><span><i style="background:var(--cyan)"></i>PERSON</span></div>`; }
function threatPanel() { return panel('Threat index', 'LIVE SCORING', `<div class="threat-score"><div class="score red">${threat}</div><span class="tier">ELEVATED</span></div><div class="meter"><div class="meter-fill" style="width:${threat}%"></div></div><div class="readout"><div class="readout-row"><span>Wildlife risk</span><span class="red">HIGH / 82</span></div><div class="readout-row"><span>Human activity</span><span>MED / 54</span></div><div class="readout-row"><span>Route exposure</span><span class="lime">LOW / 31</span></div><div class="readout-row"><span>Last recalculated</span><span>18 sec ago</span></div></div>`); }
function routePanel() { return panel('Route comparison', 'A* SOLVER', `<div class="route-card"><div><strong>Safest route</strong><small>LOW EXPOSURE / RECOMMENDED</small></div><span class="route-value">2.8 km</span></div><div class="route-line"><span></span></div><div class="route-card" style="margin-top:14px"><div><strong>Shortest route</strong><small>DIRECT LINE / HIGH EXPOSURE</small></div><span class="route-value" style="color:var(--muted)">2.1 km</span></div><div class="readout"><div class="readout-row"><span>Extra distance</span><span>+33%</span></div><div class="readout-row"><span>Risk avoided</span><span class="lime">51%</span></div></div><div class="buttons" style="margin-top:18px"><button class="button primary" data-action="route">OPEN ROUTE PLANNER</button></div>`); }
function overview() { return `<section class="hero"><div><div class="eyebrow">RoboFest for peace / ground station / unit 01</div><h1>See clearly.<br><em>Move safely.</em></h1></div><p class="lede">Aerial intelligence for peaceful surveillance, wildlife early warning and narcotics control. AI turns live footage into people counts, species alerts and routes your team can trust.</p></section><div class="metric-row">${metric(counts.people,'PEOPLE IN SECTOR','cyan')}${metric(counts.animals,'WILDLIFE','red')}${metric(counts.vehicles,'VEHICLES','amber')}${metric('94%','GPS ACCURACY','lime')}</div><div class="grid grid-main">${panel('Live sector map','2.4 KM RADIUS',map(),true)}<div class="grid">${threatPanel()}${panel('Priority alerts','3 ACTIVE',alertList(),true)}</div></div><div class="grid grid-two" style="margin-top:14px">${routePanel()}${panel('Mission telemetry','UNIT 01 / ONLINE',`<div class="readout"><div class="readout-row"><span>Mission mode</span><span class="lime">SURVEILLANCE</span></div><div class="readout-row"><span>Camera feed</span><span class="cyan">LIVE / 30 FPS</span></div><div class="readout-row"><span>AI model</span><span>COCO-SSD / READY</span></div><div class="readout-row"><span>Drone altitude</span><span>120 m AGL</span></div><div class="readout-row"><span>Coordinates</span><span>${gps.lat.toFixed(4)} N / ${gps.lng.toFixed(4)} E</span></div></div>`)}</div>`; }
function sensor() { return `<div class="page-heading"><div class="eyebrow">Module / CAM 02</div><h1>Live sensor</h1><p>On-device vision reads the feed, classifies people, animals and vehicles, then attaches an estimated range to every detection.</p></div><div class="grid grid-main"><div>${panel('Drone camera','LIVE / 30 FPS',`<div class="video"><div class="video-hud"></div><div class="video-person"></div></div><div class="buttons" style="margin-top:14px"><button class="button primary" data-action="camera">START CAMERA</button><button class="button" data-action="footage">LOAD FOOTAGE</button><button class="button" data-action="overlay">HIDE OVERLAY</button></div>`,true)}<div class="metric-row" style="margin-top:14px">${metric(counts.people,'PEOPLE','cyan')}${metric(counts.animals,'ANIMALS','red')}${metric(counts.vehicles,'VEHICLES','amber')}${metric(counts.objects,'OBJECTS','lime')}</div></div>${panel('AI detections','HIGHEST CONFIDENCE',`<table class="table"><thead><tr><th>Class</th><th>Confidence</th><th>Range</th></tr></thead><tbody><tr><td class="cyan">person</td><td>94%</td><td>180 m</td></tr><tr><td class="red">elephant</td><td>88%</td><td>1.8 km</td></tr><tr><td class="amber">car</td><td>91%</td><td>440 m</td></tr><tr><td class="lime">backpack</td><td>79%</td><td>62 m</td></tr></tbody></table><div class="readout"><div class="readout-row"><span>Model status</span><span class="lime">READY</span></div><div class="readout-row"><span>Range source</span><span>VISION + LIDAR</span></div><div class="readout-row"><span>Privacy</span><span>ON-DEVICE ONLY</span></div></div>`)}</div>`; }
function routes() { return `<div class="page-heading"><div class="eyebrow">Module / NAV 03</div><h1>Safe routing</h1><p>Compare the direct line with a risk-aware A* route that keeps clearance from contacts and wildlife corridors.</p></div><div class="grid grid-main">${panel('Tactical sector','ROUTE SOLUTIONS',map(),true)}<div class="grid">${routePanel()}${panel('Waypoint','SELECT DESTINATION',`<div class="buttons"><button class="button primary" data-action="waypoint">RANGER POST</button><button class="button">VILLAGE SCHOOL</button><button class="button">ROAD HEAD</button></div><div class="range" style="margin-top:22px"><label class="label">AVOIDANCE WEIGHT<input type="range" min="1" max="10" value="7" /></label><label class="label">ALTITUDE<input type="range" min="40" max="400" value="120" /></label></div>`)}</div></div>`; }
function alertsView() { return `<div class="page-heading"><div class="eyebrow">Module / OBJ 04</div><h1>Interdiction</h1><p>Detect unattended objects, unusual vehicle behavior and dangerous species while keeping the human operator in the loop.</p></div><div class="metric-row">${metric('01','FLAGGED OBJECT','red')}${metric('03','WILDLIFE ALERTS','amber')}${metric('08','VEHICLES TRACKED','cyan')}${metric('12','PEOPLE TRACKED','lime')}</div><div class="grid grid-two">${panel('Evidence log','TIMESTAMPED',alertList()+`<div class="buttons" style="margin-top:18px"><button class="button primary" data-action="export">EXPORT EVIDENCE LOG</button></div>`,true)}${panel('Detection policy','HUMAN REVIEW REQUIRED',`<div class="readout"><div class="readout-row"><span>Unattended object</span><span>STILL + 8 MIN</span></div><div class="readout-row"><span>Separation threshold</span><span>25 M FROM PERSON</span></div><div class="readout-row"><span>Wildlife priority</span><span class="red">ELEPHANT / TIGER</span></div><div class="readout-row"><span>Automatic action</span><span>NONE</span></div></div><p class="lede" style="font-size:13px;margin-top:22px">Flags recommend a second look. They are never a verdict.</p>`)}</div>`; }
function system() { return `<div class="page-heading"><div class="eyebrow">Module / CFG 05</div><h1>Telemetry</h1><p>Control the inputs that shape every range estimate, GPS position and route decision.</p></div><div class="grid grid-two">${panel('Platform + optics','RANGE CALIBRATION',`<div class="range"><label class="label">ALTITUDE <input type="range" min="20" max="400" value="120" /></label><label class="label">CAMERA TILT <input type="range" min="5" max="89" value="42" /></label><label class="label">HORIZONTAL FOV <input type="range" min="30" max="120" value="78" /></label><label class="label">HEADING <input type="range" min="0" max="359" value="14" /></label></div><div class="readout"><div class="readout-row"><span>GPS home</span><span>${gps.lat.toFixed(4)} N / ${gps.lng.toFixed(4)} E</span></div><div class="readout-row"><span>Focal length</span><span>836 PX</span></div></div>`)}${panel('System health','ALL NOMINAL',`<div class="readout"><div class="readout-row"><span>GPS lock</span><span class="lime">3D / 14 SATELLITES</span></div><div class="readout-row"><span>Camera link</span><span class="cyan">CONNECTED</span></div><div class="readout-row"><span>AI inference</span><span class="lime">30 FPS</span></div><div class="readout-row"><span>LiDAR rangefinder</span><span class="amber">SIMULATED</span></div><div class="readout-row"><span>Route solver</span><span class="lime">READY</span></div></div><div class="buttons" style="margin-top:20px"><button class="button secondary" data-action="gps">REFRESH GPS</button></div>`)}</div>`; }
function render(view = activeView) { activeView = view; const pages = { overview, sensor, routes, alerts: alertsView, system }; app.innerHTML = pages[view](); document.querySelectorAll('.nav-item').forEach(el => el.classList.toggle('active', el.dataset.view === view)); bindActions(); }
function toast(message) { const el = document.createElement('div'); el.className = 'toast'; el.textContent = message; document.body.appendChild(el); setTimeout(() => el.remove(), 2600); }
function bindActions() { document.querySelectorAll('[data-action]').forEach(button => button.addEventListener('click', () => { const action = button.dataset.action; if (action === 'camera') toast('Camera permission requested'); if (action === 'footage') videoInput.click(); if (action === 'overlay') { button.textContent = button.textContent.includes('HIDE') ? 'SHOW OVERLAY' : 'HIDE OVERLAY'; toast('Detection overlay updated'); } if (action === 'route') { render('routes'); toast('Route planner opened'); } if (action === 'gps') requestGps(); if (action === 'export') toast('Evidence log prepared for export'); if (action === 'waypoint') toast('Waypoint set: Ranger post'); })); }
function requestGps() { if (!navigator.geolocation) return toast('GPS is unavailable in this browser'); navigator.geolocation.getCurrentPosition(position => { gps = { lat: position.coords.latitude, lng: position.coords.longitude, source: 'DEVICE GPS' }; toast('GPS position updated'); render(activeView); }, () => toast('GPS permission was not granted')); }
document.querySelectorAll('.nav-item').forEach(el => el.addEventListener('click', e => { e.preventDefault(); render(el.dataset.view); history.replaceState(null, '', el.getAttribute('href')); }));
document.querySelector('#gpsButton').addEventListener('click', requestGps);
videoInput.addEventListener('change', e => { if (e.target.files[0]) toast(`Loaded ${e.target.files[0].name}`); });
setInterval(() => { document.querySelector('#clock').textContent = `${new Date().toISOString().slice(11, 19)} UTC`; }, 1000);
setInterval(() => { threat = Math.max(55, Math.min(79, threat + (Math.random() > .5 ? 1 : -1))); if (activeView === 'overview') { const score = document.querySelector('.score'); const fill = document.querySelector('.meter-fill'); if (score) score.textContent = threat; if (fill) fill.style.width = `${threat}%`; } }, 4000);
let activeMode = 'drone';
let droneAngle = 0;

function modeToggle() {
  return `<div class="mode-toggle"><button class="${activeMode === 'drone' ? 'selected' : ''}" data-action="drone-mode">DRONE VIEW</button><button class="${activeMode === 'user' ? 'selected' : ''}" data-action="user-mode">USER VIEW</button></div>`;
}

function cameraView() {
  return `<div class="camera"><div class="camera-scan"></div><div class="camera-hud"><span>CAM 01 / FORWARD</span><span class="rec">● REC / DEMO</span></div><span class="crosshair"></span><span class="box box-0 cyan"><b>PERSON / 18 m</b><small>NORTH-EAST · 94% · ID P-08</small></span><span class="box box-1 red"><b>ELEPHANT / 1.8 km</b><small>NORTH-EAST · 88% · ID W-03</small></span><span class="box box-2 amber"><b>VEHICLE / 42 m</b><small>EAST · 91% · ID V-12</small></span><div class="camera-footer">ALT 120 m AGL <span>HEADING 014°</span><span>FOV 78°</span></div></div>`;
}

function lidarView() {
  return `<div class="lidar"><div class="lidar-sweep"></div><div class="lidar-cross"></div><span class="lidar-point lp1">8m</span><span class="lidar-point lp2">21m</span><span class="lidar-point lp3">14m</span><b class="lidar-core">DRONE</b><span class="lidar-dir front">FRONT<br><strong class="lime">CLEAR · 32 m</strong></span><span class="lidar-dir left">LEFT<br><strong class="red">OBSTACLE · 8 m</strong></span><span class="lidar-dir right">RIGHT<br><strong class="lime">CLEAR · 25 m</strong></span><span class="lidar-dir rear">REAR<br><strong class="amber">TREE · 14 m</strong></span></div>`;
}

function fusionPanel() {
  return panel('Sensor fusion', 'ALL SYSTEMS NOMINAL', `<div class="fusion-grid"><span><i class="ok"></i>CAMERA<small>ONLINE</small></span><span><i class="ok"></i>LIDAR 1<small>ONLINE</small></span><span><i class="ok"></i>LIDAR 2<small>ONLINE</small></span><span><i class="ok"></i>GPS<small>LOCKED</small></span><span><i class="ok"></i>AI VISION<small>ACTIVE</small></span><span><i class="ok"></i>MAP<small>LIVE</small></span></div>`);
}

function environmentPanel() {
  return panel('What is around you?', 'WITHIN 500 M', `<div class="nearby-grid"><span><b>18</b>People nearby</span><span><b>6</b>Vehicles nearby</span><span><b>2</b>Dogs nearby</span><span><b>31</b>Trees nearby</span><span><b>4</b>Buildings nearby</span><span><b class="lime">3</b>Safe areas nearby</span></div><p class="disclaimer">AI recommendations use current sensor data and are not guaranteed safe. Verify conditions with local authorities.</p>`);
}

function navigationPanel() {
  return panel('User navigation', 'SAFE ROUTE / 420 m', `<div class="nav-instruction"><span class="nav-arrow">↗</span><div><small>NEXT</small><strong>MOVE FORWARD 120 m</strong><p>“Proceed forward for 120 meters, then turn left.”</p></div></div><div class="nav-step"><span>02</span>THEN: TURN LEFT <b>85 m</b></div><div class="nav-step"><span>03</span>SAFE ZONE AHEAD <b class="cyan">210 m</b></div><button class="button primary" data-action="nav">START SAFE NAVIGATION</button>`);
}

function droneModel() {
  return panel('3D drone model', 'COMPONENT VIEW', `<div class="drone-stage"><div class="drone-model" style="transform:rotateX(58deg) rotateZ(${droneAngle}deg)"><div class="drone-body"></div><i class="arm arm-a"></i><i class="arm arm-b"></i><i class="arm arm-c"></i><i class="arm arm-d"></i><i class="prop prop-a"></i><i class="prop prop-b"></i><i class="prop prop-c"></i><i class="prop prop-d"></i><span class="drone-camera">CAM</span><span class="module-label label-camera">CAMERA</span><span class="module-label label-gps">GPS MODULE</span><span class="module-label label-lidar">LIDAR ×2</span></div></div><button class="button" data-action="rotate">ROTATE MODEL</button>`);
}

function enhancedOverview() {
  return `<section class="hero"><div><div class="eyebrow">Drone for world peace / ground station / unit 01</div><h1>See clearly.<br><em>Move safely.</em></h1></div><div><p class="lede">AI surveillance, safety and emergency navigation for peaceful public safety, search-and-rescue, wildlife monitoring and disaster response.</p>${modeToggle()}</div></section><div class="demo-banner"><span>DEMO / SIMULATION</span> No physical drone connected. Values are simulated for presentation. <b>Privacy-first, human-reviewed recommendations.</b></div><div class="grid grid-main"><div class="grid">${panel(activeMode === 'drone' ? 'Drone camera view' : 'User surroundings', activeMode === 'drone' ? 'FORWARD CAMERA / AI OVERLAY' : 'GPS / YOU ARE HERE', activeMode === 'drone' ? cameraView() : map(), true)}${activeMode === 'drone' ? droneModel() : navigationPanel()}</div><div class="grid">${analysisPanel()}${panel('LiDAR sensor view', '2 SENSORS / 360° AWARENESS', lidarView(), true)}${fusionPanel()}</div></div><div class="grid grid-main" style="margin-top:14px"><div class="grid">${panel('3D GPS map', '8 KM MONITORING RADIUS', map(), true)}${environmentPanel()}</div><div class="grid">${threatPanel()}${navigationPanel()}${missionPanel()}${controlPanel()}</div></div><div class="grid grid-two" style="margin-top:14px">${panel('Emergency and safety alerts', 'HUMAN REVIEW REQUIRED', alertList(), true)}${panel('How the system reasons', 'CAMERA + LIDAR + GPS + AI', `<div class="flow"><span>CAMERA<small>SEES</small></span><b>→</b><span>LIDAR<small>CONFIRMS</small></span><b>→</b><span>GPS<small>MAPS</small></span><b>→</b><span>AI<small>ASSISTS</small></span></div><p class="disclaimer">The system supports observation and assistance. It does not guarantee safety or replace emergency services.</p>`)}</div>`;
}

function analysisPanel() {
  return panel('AI environment analysis', 'MODEL ACTIVE / 30 FPS', `<div class="analysis-grid">${metric(12, 'PEOPLE', 'cyan')}${metric(5, 'VEHICLES', 'amber')}${metric(3, 'ANIMALS', 'red')}${metric(47, 'TREES', 'lime')}${metric(8, 'BUILDINGS', 'cyan')}${metric(6, 'OBSTACLES', 'red')}</div><div class="species">ANIMALS <b>DOG 1</b><b>ELEPHANT 2</b> · VEHICLES <b>CAR 3</b><b>MOTORCYCLE 2</b></div>`);
}

function missionPanel() { return panel('Mission: peaceful surveillance', 'DEMO / SIMULATION', `<div class="mission-grid"><span>MISSION ID<b>PEACE-07-A</b></span><span>ALTITUDE<b>120 m AGL</b></span><span>BATTERY<b class="lime">82%</b></span><span>FLIGHT TIME<b>18:42</b></span><span>SPEED<b>4.8 m/s</b></span><span>SIGNAL<b class="cyan">98%</b></span><span>DESTINATION<b>RANGER POST</b></span><span>MODE<b class="lime">AUTONOMOUS</b></span></div>`); }

function controlPanel() { return panel('Drone control', 'MANUAL / AUTONOMOUS', `<div class="control-modes"><button class="button primary">MANUAL MODE</button><button class="button">AUTONOMOUS MODE</button></div><div class="dpad"><button data-action="control">↑<small>FORWARD</small></button><button data-action="control">←<small>LEFT</small></button><button data-action="control">●<small>HOVER</small></button><button data-action="control">→<small>RIGHT</small></button><button data-action="control">↓<small>BACK</small></button></div><div class="buttons control-actions"><button class="button" data-action="control">↥ UP</button><button class="button" data-action="control">↧ DOWN</button><button class="button secondary" data-action="control">RETURN HOME</button><button class="button emergency" data-action="emergency">EMERGENCY STOP</button></div>`); }

function enhancedBindActions() {
  document.querySelectorAll('[data-action]').forEach(button => button.addEventListener('click', () => { const action = button.dataset.action; if (action === 'drone-mode') { activeMode = 'drone'; render(); } if (action === 'user-mode') { activeMode = 'user'; render(); } if (action === 'rotate') { droneAngle += 45; render(); } if (action === 'nav') toast('Safe navigation active: proceed forward 120 m'); if (action === 'emergency') toast('Emergency stop simulated: drone held in hover'); if (action === 'control') toast('Control command sent to demo drone'); }));
}

const originalRender = render;
render = function(view = activeView) { if (view === 'overview') { activeView = view; app.innerHTML = enhancedOverview(); document.querySelectorAll('.nav-item').forEach(el => el.classList.toggle('active', el.dataset.view === view)); enhancedBindActions(); return; } originalRender(view); };
render(location.hash ? ({ '#sensor':'sensor', '#routes':'routes', '#alerts':'alerts', '#system':'system' }[location.hash] || 'overview') : 'overview');
